export type DemoBrandId = 'hm' | 'zara' | 'amazon';

export type DemoProduct = {
  id: string;
  brand: DemoBrandId;
  name: string;
  price: number;
  compareAtPrice: number;
  sku: string;
  description: string;
  image: string;
  colorImages?: Record<string, string>;
  category: 'Best Sellers' | 'New Arrivals' | 'Shirts' | 'Pants' | 'Dresses' | 'Jackets' | 'Accessories';
  sizes: string[];
  colors: string[];
  stockStatus: 'In stock' | 'Low stock' | 'Last units';
};

export type DemoStore = {
  id: DemoBrandId;
  name: string;
  tagline: string;
  deliveryEta: string;
  accent: string;
  logoText: string;
  heroImage: string;
};

export const FREE_SHIPPING_GOAL = 400;
export const DELIVERY_FEE = 25;

export const demoStores: Record<DemoBrandId, DemoStore> = {
  hm: {
    id: 'hm',
    name: 'H&M',
    tagline: 'Everyday fashion, consolidated by Shakana',
    deliveryEta: '35-50 min merchant handling',
    accent: '#D4001A',
    logoText: 'H&M',
    heroImage:
      'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=1400&q=80',
  },
  zara: {
    id: 'zara',
    name: 'Zara',
    tagline: 'Premium city wardrobe, one shared delivery',
    deliveryEta: '40-55 min merchant handling',
    accent: '#111111',
    logoText: 'ZARA',
    heroImage:
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1400&q=80',
  },
  amazon: {
    id: 'amazon',
    name: 'Amazon',
    tagline: 'One-link invite for essentials and wardrobe basics',
    deliveryEta: 'Prime-style rapid fulfillment',
    accent: '#111111',
    logoText: 'A',
    heroImage:
      'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=1400&q=80',
  },
};

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;

export function getProductImage(product: DemoProduct, color?: string): string {
  const variantImage = color ? product.colorImages?.[color] : undefined;
  if (variantImage) return variantImage;
  return product.image;
}

export const demoProducts: DemoProduct[] = [
  // ── H&M ─────────────────────────────────────────────────────────────────────
  {
    id: 'hm-linen-shirt',
    brand: 'hm',
    name: 'H&M Linen-Blend Shirt',
    price: 119,
    compareAtPrice: 139,
    sku: 'HM-SH-1048',
    description: 'Lightweight linen-blend button-up with a relaxed resort fit.',
    image: img('photo-1603252109303-2751441dd157'),
    colorImages: {
      White: img('photo-1603252109303-2751441dd157'),
      Sage: img('photo-1598300042247-d088f8ab3a91'),
      'Sky Blue': img('photo-1620799140408-edc6dcb6d633'),
    },
    category: 'Best Sellers',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Sage', 'Sky Blue'],
    stockStatus: 'In stock',
  },
  {
    id: 'hm-wide-jeans',
    brand: 'hm',
    name: 'H&M Wide High Jeans',
    price: 159,
    compareAtPrice: 189,
    sku: 'HM-DN-8821',
    description: 'Wide-leg denim with a high waist and soft washed finish.',
    image: img('photo-1541099649105-f69ad21f3246'),
    colorImages: {
      Blue: img('photo-1541099649105-f69ad21f3246'),
      'Washed Black': img('photo-1525507119028-ed4c629a60a3'),
    },
    category: 'Pants',
    sizes: ['30', '32', '34', '36', '38', '40'],
    colors: ['Blue', 'Washed Black'],
    stockStatus: 'Low stock',
  },
  {
    id: 'hm-rib-dress',
    brand: 'hm',
    name: 'H&M Rib-Knit Midi Dress',
    price: 129,
    compareAtPrice: 149,
    sku: 'HM-DR-3320',
    description: 'Soft ribbed dress with clean neckline and weekend-ready stretch.',
    image: img('photo-1515372039744-b8f02a3ae446'),
    colorImages: {
      Black: img('photo-1517438476312-10d79c077509'),
      Cream: img('photo-1554568218-0f1715e72254'),
      Brown: img('photo-1509631179647-0177331693ae'),
    },
    category: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Cream', 'Brown'],
    stockStatus: 'In stock',
  },
  {
    id: 'hm-cargo-trousers',
    brand: 'hm',
    name: 'H&M Relaxed Cargo Trousers',
    price: 149,
    compareAtPrice: 169,
    sku: 'HM-PT-7714',
    description: 'Cotton twill cargo trousers with adjustable hems and utility pockets.',
    image: img('photo-1506629905607-d405d7d3b0d2'),
    category: 'New Arrivals',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Khaki', 'Black', 'Stone'],
    stockStatus: 'Last units',
  },
  {
    id: 'hm-basic-tee',
    brand: 'hm',
    name: 'H&M Premium Cotton T-Shirt',
    price: 49,
    compareAtPrice: 59,
    sku: 'HM-TS-2105',
    description: 'Dense cotton jersey tee with a straight fit and soft neckline.',
    image: img('photo-1521572163474-6864f9cf17ab'),
    colorImages: {
      White: img('photo-1521572163474-6864f9cf17ab'),
      Black: img('photo-1516575334481-f85287c2c82d'),
      Red: img('photo-1572804013309-59a88b7e92f1'),
      Navy: img('photo-1506792006437-256b665541e2'),
    },
    category: 'Shirts',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Red', 'Navy'],
    stockStatus: 'In stock',
  },
  {
    id: 'hm-crossbody',
    brand: 'hm',
    name: 'H&M Quilted Crossbody Bag',
    price: 99,
    compareAtPrice: 119,
    sku: 'HM-AC-6673',
    description: 'Compact quilted bag with zip closure and adjustable strap.',
    image: img('photo-1591561954557-26941169b49e'),
    category: 'Accessories',
    sizes: ['One size'],
    colors: ['Black', 'Beige', 'Burgundy'],
    stockStatus: 'In stock',
  },
  {
    id: 'hm-oversized-hoodie',
    brand: 'hm',
    name: 'H&M Oversized Fleece Hoodie',
    price: 139,
    compareAtPrice: 159,
    sku: 'HM-HD-3301',
    description: 'Drop-shoulder hoodie in brushed fleece with a kangaroo pocket.',
    image: img('photo-1556821840-3a63f95609a7'),
    colorImages: {
      Oatmeal: img('photo-1556821840-3a63f95609a7'),
      Charcoal: img('photo-1505022610485-0249ba5b3675'),
      'Dusty Pink': img('photo-1551163943-3f6a855d1153'),
    },
    category: 'Best Sellers',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Oatmeal', 'Charcoal', 'Dusty Pink'],
    stockStatus: 'In stock',
  },
  {
    id: 'hm-polo-shirt',
    brand: 'hm',
    name: 'H&M Piqué Polo Shirt',
    price: 79,
    compareAtPrice: 99,
    sku: 'HM-PL-4410',
    description: 'Classic piqué polo with a slim collar and button placket.',
    image: img('photo-1490481651871-ab68de25d43d'),
    colorImages: {
      Navy: img('photo-1506792006437-256b665541e2'),
      White: img('photo-1583744946564-b52ac1c389c8'),
      'Forest Green': img('photo-1614676471928-2ed0ad1061a4'),
      Burgundy: img('photo-1544441892-794166f1e3be'),
    },
    category: 'Shirts',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'White', 'Forest Green', 'Burgundy'],
    stockStatus: 'In stock',
  },
  {
    id: 'hm-canvas-tote',
    brand: 'hm',
    name: 'H&M Structured Canvas Tote',
    price: 89,
    compareAtPrice: 109,
    sku: 'HM-AC-7712',
    description: 'Heavy canvas tote with internal zip pocket and reinforced handles.',
    image: img('photo-1544816565-aa8c1166648f'),
    category: 'Accessories',
    sizes: ['One size'],
    colors: ['Natural', 'Black', 'Olive'],
    stockStatus: 'In stock',
  },
  {
    id: 'hm-blazer',
    brand: 'hm',
    name: 'H&M Relaxed Fit Blazer',
    price: 299,
    compareAtPrice: 349,
    sku: 'HM-BL-5509',
    description: 'Single-button blazer in a boxy silhouette, perfect for layering.',
    image: img('photo-1507679799987-c73779587ccf'),
    category: 'Jackets',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Camel', 'Checked'],
    stockStatus: 'Low stock',
  },
  {
    id: 'hm-knit-cardigan',
    brand: 'hm',
    name: 'H&M Ribbed Knit Cardigan',
    price: 169,
    compareAtPrice: 199,
    sku: 'HM-KN-6621',
    description: 'Open-front ribbed cardigan with dropped shoulders and long sleeves.',
    image: img('photo-1434389677669-e08b4cac3105'),
    category: 'New Arrivals',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Cream', 'Mocha', 'Slate Blue'],
    stockStatus: 'In stock',
  },
  {
    id: 'hm-floral-dress',
    brand: 'hm',
    name: 'H&M Floral Wrap Dress',
    price: 149,
    compareAtPrice: 179,
    sku: 'HM-DR-9901',
    description: 'V-neck wrap dress in a lightweight woven fabric with floral print.',
    image: img('photo-1573497620053-ea5300f94f21'),
    category: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Blue Floral', 'Pink Floral', 'Black Floral'],
    stockStatus: 'In stock',
  },
  {
    id: 'hm-slim-chinos',
    brand: 'hm',
    name: 'H&M Slim Fit Chinos',
    price: 129,
    compareAtPrice: 149,
    sku: 'HM-PT-2287',
    description: 'Slim-cut chinos in a stretch cotton blend with a clean finish.',
    image: img('photo-1473966968600-fa801b869a1a'),
    category: 'Pants',
    sizes: ['30', '32', '34', '36', '38'],
    colors: ['Beige', 'Olive', 'Navy', 'Black'],
    stockStatus: 'In stock',
  },
  {
    id: 'hm-puffer-jacket',
    brand: 'hm',
    name: 'H&M Lightweight Puffer Jacket',
    price: 249,
    compareAtPrice: 299,
    sku: 'HM-JK-1144',
    description: 'Channel-quilted puffer in a lightweight shell that packs flat.',
    image: img('photo-1548126032-079a0fb0099d'),
    category: 'Jackets',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Khaki', 'Cobalt Blue'],
    stockStatus: 'Last units',
  },
  {
    id: 'hm-crop-top',
    brand: 'hm',
    name: 'H&M Ribbed Crop Top',
    price: 59,
    compareAtPrice: 69,
    sku: 'HM-TS-3390',
    description: 'Fitted ribbed crop top with a square neckline and short sleeves.',
    image: img('photo-1576566588028-4147f3842f27'),
    colorImages: {
      White: img('photo-1583744946564-b52ac1c389c8'),
      Black: img('photo-1516575334481-f85287c2c82d'),
      Terracotta: img('photo-1617127365659-c47fa864d8bc'),
      Lilac: img('photo-1551163943-3f6a855d1153'),
    },
    category: 'Shirts',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Black', 'Terracotta', 'Lilac'],
    stockStatus: 'In stock',
  },
  {
    id: 'hm-sneakers',
    brand: 'hm',
    name: 'H&M Canvas Low Sneakers',
    price: 119,
    compareAtPrice: 139,
    sku: 'HM-FW-8801',
    description: 'Vulcanised canvas sneakers with a clean low profile and rubber sole.',
    image: img('photo-1549298916-b41d501d3772'),
    category: 'Accessories',
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44'],
    colors: ['White', 'Black', 'Navy'],
    stockStatus: 'In stock',
  },

  // ── Zara ─────────────────────────────────────────────────────────────────────
  {
    id: 'zara-basic-tee',
    brand: 'zara',
    name: 'Zara Basic Heavy T-Shirt',
    price: 89,
    compareAtPrice: 109,
    sku: 'ZA-TS-4102',
    description: 'Heavy cotton T-shirt with a boxy silhouette and premium hand feel.',
    image: img('photo-1503342217505-b0a15ec3261c'),
    colorImages: {
      Black: img('photo-1503342217505-b0a15ec3261c'),
      White: img('photo-1583744946564-b52ac1c389c8'),
      Taupe: img('photo-1554568218-0f1715e72254'),
    },
    category: 'Best Sellers',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'White', 'Taupe'],
    stockStatus: 'In stock',
  },
  {
    id: 'zara-tailored-pants',
    brand: 'zara',
    name: 'Zara Tailored Straight Pants',
    price: 229,
    compareAtPrice: 259,
    sku: 'ZA-PT-9027',
    description: 'Straight tailored pants with pressed crease and concealed fastening.',
    image: img('photo-1594633312681-425c7b97ccd1'),
    category: 'Pants',
    sizes: ['32', '34', '36', '38', '40', '42'],
    colors: ['Black', 'Charcoal', 'Sand'],
    stockStatus: 'Low stock',
  },
  {
    id: 'zara-poplin-shirt',
    brand: 'zara',
    name: 'Zara Oversized Poplin Shirt',
    price: 179,
    compareAtPrice: 199,
    sku: 'ZA-SH-5539',
    description: 'Crisp poplin shirt with dropped shoulders and long cuffs.',
    image: img('photo-1602810318383-e386cc2a3ccf'),
    colorImages: {
      White: img('photo-1602810318383-e386cc2a3ccf'),
      'Blue Stripe': img('photo-1620799140408-edc6dcb6d633'),
      Black: img('photo-1516575334481-f85287c2c82d'),
    },
    category: 'Shirts',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Blue Stripe', 'Black'],
    stockStatus: 'In stock',
  },
  {
    id: 'zara-slip-dress',
    brand: 'zara',
    name: 'Zara Satin Slip Dress',
    price: 249,
    compareAtPrice: 279,
    sku: 'ZA-DR-1180',
    description: 'Fluid satin midi dress with adjustable straps and clean drape.',
    image: img('photo-1539008835657-9e8e9680c956'),
    colorImages: {
      Ivory: img('photo-1539008835657-9e8e9680c956'),
      Black: img('photo-1517438476312-10d79c077509'),
      'Deep Green': img('photo-1598300042247-d088f8ab3a91'),
    },
    category: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ivory', 'Black', 'Deep Green'],
    stockStatus: 'In stock',
  },
  {
    id: 'zara-denim-jacket',
    brand: 'zara',
    name: 'Zara Cropped Denim Jacket',
    price: 299,
    compareAtPrice: 329,
    sku: 'ZA-JK-7082',
    description: 'Cropped denim jacket with structured shoulders and metal buttons.',
    image: img('photo-1551028719-00167b16eac5'),
    category: 'Jackets',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Mid Blue', 'Ecru'],
    stockStatus: 'Last units',
  },
  {
    id: 'zara-leather-belt',
    brand: 'zara',
    name: 'Zara Leather Belt',
    price: 119,
    compareAtPrice: 139,
    sku: 'ZA-AC-3305',
    description: 'Smooth leather belt with brushed metal buckle.',
    image: img('photo-1553062407-98eeb64c6a62'),
    category: 'Accessories',
    sizes: ['80', '85', '90', '95'],
    colors: ['Black', 'Brown'],
    stockStatus: 'In stock',
  },
  {
    id: 'zara-knit-sweater',
    brand: 'zara',
    name: 'Zara Chunky Knit Sweater',
    price: 219,
    compareAtPrice: 259,
    sku: 'ZA-KN-2201',
    description: 'Oversized chunky-knit sweater with a wide crew neck and drop shoulders.',
    image: img('photo-1598033129183-c4f50c736f10'),
    colorImages: {
      Ecru: img('photo-1598033129183-c4f50c736f10'),
      Camel: img('photo-1509631179647-0177331693ae'),
      Black: img('photo-1516575334481-f85287c2c82d'),
    },
    category: 'Best Sellers',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ecru', 'Camel', 'Black'],
    stockStatus: 'In stock',
  },
  {
    id: 'zara-blazer-set',
    brand: 'zara',
    name: 'Zara Structured Blazer',
    price: 349,
    compareAtPrice: 399,
    sku: 'ZA-BL-8810',
    description: 'Double-breasted blazer with peak lapels and a tailored silhouette.',
    image: img('photo-1539109136881-3be0616acf4b'),
    category: 'Jackets',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Pinstripe', 'Camel'],
    stockStatus: 'Low stock',
  },
  {
    id: 'zara-midi-skirt',
    brand: 'zara',
    name: 'Zara Pleated Midi Skirt',
    price: 199,
    compareAtPrice: 229,
    sku: 'ZA-SK-4470',
    description: 'Pleated midi skirt with an elastic waistband and fluid drape.',
    image: img('photo-1583496661160-fb5974ca0e68'),
    category: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Blush', 'Cobalt'],
    stockStatus: 'In stock',
  },
  {
    id: 'zara-leather-tote',
    brand: 'zara',
    name: 'Zara City Leather Tote',
    price: 399,
    compareAtPrice: 449,
    sku: 'ZA-AC-9901',
    description: 'Structured tote in pebbled leather with a zip top and inner compartments.',
    image: img('photo-1548036328-c9fa89d128fa'),
    category: 'Accessories',
    sizes: ['One size'],
    colors: ['Black', 'Tan', 'Burgundy'],
    stockStatus: 'Low stock',
  },
  {
    id: 'zara-ribbed-top',
    brand: 'zara',
    name: 'Zara Ribbed Fitted Top',
    price: 99,
    compareAtPrice: 119,
    sku: 'ZA-TS-6630',
    description: 'Slim ribbed top with a mock neck and clean elongated cut.',
    image: img('photo-1515886657613-9f3515b0c78f'),
    category: 'Shirts',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'White', 'Mushroom'],
    stockStatus: 'In stock',
  },
  {
    id: 'zara-printed-dress',
    brand: 'zara',
    name: 'Zara Abstract Print Dress',
    price: 279,
    compareAtPrice: 319,
    sku: 'ZA-DR-3345',
    description: 'Long-sleeve midi dress in an abstract print with a v-neck and tie waist.',
    image: img('photo-1583743814966-8936f5b7be1a'),
    category: 'New Arrivals',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Blue Print', 'Black Print'],
    stockStatus: 'Last units',
  },
  {
    id: 'zara-wide-trousers',
    brand: 'zara',
    name: 'Zara Wide-Leg Trousers',
    price: 249,
    compareAtPrice: 279,
    sku: 'ZA-PT-7750',
    description: 'High-rise wide-leg trousers in a crêpe fabric with side pockets.',
    image: img('photo-1525507119028-ed4c629a60a3'),
    category: 'Pants',
    sizes: ['34', '36', '38', '40', '42'],
    colors: ['Black', 'Ivory', 'Chocolate'],
    stockStatus: 'In stock',
  },
  {
    id: 'zara-trench-coat',
    brand: 'zara',
    name: 'Zara Classic Trench Coat',
    price: 499,
    compareAtPrice: 579,
    sku: 'ZA-JK-1102',
    description: 'Belted double-breasted trench in water-resistant gabardine.',
    image: img('photo-1578662996442-48f60103fc96'),
    category: 'Jackets',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Camel', 'Black', 'Khaki'],
    stockStatus: 'In stock',
  },
  {
    id: 'zara-watch',
    brand: 'zara',
    name: 'Zara Minimalist Watch',
    price: 299,
    compareAtPrice: 349,
    sku: 'ZA-AC-5512',
    description: 'Quartz watch with a slim case, mesh strap, and clean dial.',
    image: img('photo-1475180098004-ca77a66827be'),
    category: 'Accessories',
    sizes: ['One size'],
    colors: ['Silver', 'Gold', 'Rose Gold'],
    stockStatus: 'In stock',
  },
  {
    id: 'zara-barrel-jeans',
    brand: 'zara',
    name: 'Zara Barrel Fit Jeans',
    price: 259,
    compareAtPrice: 299,
    sku: 'ZA-DN-4401',
    description: 'Relaxed barrel-leg denim with a high waist and tapered ankle.',
    image: img('photo-1581091226825-a6a2a5aee158'),
    category: 'New Arrivals',
    sizes: ['32', '34', '36', '38', '40'],
    colors: ['Light Wash', 'Dark Wash', 'Ecru'],
    stockStatus: 'Low stock',
  },

  // ── Amazon ───────────────────────────────────────────────────────────────────
  {
    id: 'amazon-essential-tee',
    brand: 'amazon',
    name: 'Amazon Everyday Tee',
    price: 69,
    compareAtPrice: 79,
    sku: 'AM-TS-1001',
    description: 'Soft everyday tee with simple fit and fast replenishment.',
    image: img('photo-1521572267360-ee0c2909d518'),
    colorImages: {
      Black: img('photo-1516575334481-f85287c2c82d'),
      White: img('photo-1583744946564-b52ac1c389c8'),
      Grey: img('photo-1505022610485-0249ba5b3675'),
    },
    category: 'Best Sellers',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'White', 'Grey'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-soft-hoodie',
    brand: 'amazon',
    name: 'Amazon Soft Fleece Hoodie',
    price: 129,
    compareAtPrice: 149,
    sku: 'AM-HD-2208',
    description: 'Brushed fleece hoodie with roomy hood and clean seams.',
    image: img('photo-1483985988355-763728e1935b'),
    category: 'New Arrivals',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Oatmeal', 'Navy'],
    stockStatus: 'Low stock',
  },
  {
    id: 'amazon-straight-denim',
    brand: 'amazon',
    name: 'Amazon Straight Denim',
    price: 119,
    compareAtPrice: 139,
    sku: 'AM-DN-3390',
    description: 'Straight denim with comfort stretch and clean wash.',
    image: img('photo-1553689586-bb3dba1a6ef5'),
    category: 'Pants',
    sizes: ['30', '32', '34', '36', '38'],
    colors: ['Blue', 'Black'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-mini-pack',
    brand: 'amazon',
    name: 'Amazon 3-Pack Socks',
    price: 39,
    compareAtPrice: 49,
    sku: 'AM-AC-0051',
    description: 'Utility 3-pack with stretch fit and quick delivery.',
    image: img('photo-1586350977771-b3b0abd50c82'),
    category: 'Accessories',
    sizes: ['One size'],
    colors: ['White', 'Black'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-zip-hoodie',
    brand: 'amazon',
    name: 'Amazon Full-Zip Hoodie',
    price: 149,
    compareAtPrice: 169,
    sku: 'AM-HD-3310',
    description: 'Full-zip hoodie in heavyweight fleece with media-friendly pockets.',
    image: img('photo-1607522370275-f14206abe5d3'),
    colorImages: {
      Grey: img('photo-1607522370275-f14206abe5d3'),
      Black: img('photo-1505022610485-0249ba5b3675'),
      'Dark Green': img('photo-1614676471928-2ed0ad1061a4'),
    },
    category: 'Best Sellers',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Grey', 'Black', 'Dark Green'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-polo',
    brand: 'amazon',
    name: 'Amazon Classic Polo',
    price: 89,
    compareAtPrice: 99,
    sku: 'AM-PL-4402',
    description: 'Moisture-wicking piqué polo for everyday wear or smart casual.',
    image: img('photo-1622519407650-3df9883f76a5'),
    category: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'White', 'Black', 'Red'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-chinos',
    brand: 'amazon',
    name: 'Amazon Stretch Chinos',
    price: 109,
    compareAtPrice: 129,
    sku: 'AM-PT-5501',
    description: 'Flat-front stretch chinos with a comfortable slim taper.',
    image: img('photo-1593030761757-71fae45fa0e7'),
    category: 'Pants',
    sizes: ['30', '32', '34', '36', '38'],
    colors: ['Khaki', 'Navy', 'Olive', 'Black'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-bomber',
    brand: 'amazon',
    name: 'Amazon Varsity Bomber Jacket',
    price: 179,
    compareAtPrice: 209,
    sku: 'AM-JK-6601',
    description: 'Satin bomber with ribbed collar, cuffs, and hem in a relaxed fit.',
    image: img('photo-1591047139829-d91aecb6caea'),
    colorImages: {
      Black: img('photo-1551488831-00ddcb6c6bd3'),
      Navy: img('photo-1591047139829-d91aecb6caea'),
      Olive: img('photo-1614676471928-2ed0ad1061a4'),
    },
    category: 'Jackets',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Olive'],
    stockStatus: 'Low stock',
  },
  {
    id: 'amazon-sneakers',
    brand: 'amazon',
    name: 'Amazon Court Sneakers',
    price: 149,
    compareAtPrice: 179,
    sku: 'AM-FW-7701',
    description: 'Vulcanised court sneaker in canvas with a padded ankle collar.',
    image: img('photo-1542291026-7eec264c27ff'),
    category: 'Accessories',
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
    colors: ['White', 'Black', 'Red'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-cap',
    brand: 'amazon',
    name: 'Amazon Structured Baseball Cap',
    price: 59,
    compareAtPrice: 69,
    sku: 'AM-AC-8801',
    description: 'Six-panel structured cap with an adjustable snapback closure.',
    image: img('photo-1521369909029-2afed882baaa'),
    category: 'Accessories',
    sizes: ['One size'],
    colors: ['Black', 'Navy', 'White'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-fleece-vest',
    brand: 'amazon',
    name: 'Amazon Fleece Vest',
    price: 99,
    compareAtPrice: 119,
    sku: 'AM-JK-9902',
    description: 'Zip-up fleece vest with two hand pockets and a clean collar.',
    image: img('photo-1614676471928-2ed0ad1061a4'),
    category: 'Jackets',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Grey', 'Black', 'Forest'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-joggers',
    brand: 'amazon',
    name: 'Amazon Tapered Joggers',
    price: 99,
    compareAtPrice: 119,
    sku: 'AM-PT-1102',
    description: 'French terry joggers with a tapered leg and adjustable waistband.',
    image: img('photo-1520195527285-b394c2d07789'),
    category: 'New Arrivals',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Charcoal', 'Black', 'Navy'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-graphic-tee',
    brand: 'amazon',
    name: 'Amazon Graphic Tee',
    price: 79,
    compareAtPrice: 89,
    sku: 'AM-TS-2205',
    description: 'Heavyweight jersey tee with a chest graphic and relaxed boxy fit.',
    image: img('photo-1571945153237-4929e783af4a'),
    category: 'Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Washed Grey'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-backpack',
    brand: 'amazon',
    name: 'Amazon Everyday Backpack',
    price: 169,
    compareAtPrice: 199,
    sku: 'AM-AC-5502',
    description: '25L backpack with a padded laptop sleeve and multiple organiser pockets.',
    image: img('photo-1553062407-98eeb64c6a61'),
    category: 'Accessories',
    sizes: ['One size'],
    colors: ['Black', 'Grey', 'Navy'],
    stockStatus: 'In stock',
  },
  {
    id: 'amazon-maxi-dress',
    brand: 'amazon',
    name: 'Amazon Flowy Maxi Dress',
    price: 129,
    compareAtPrice: 149,
    sku: 'AM-DR-3301',
    description: 'Lightweight woven maxi dress with adjustable straps and a tiered hem.',
    image: img('photo-1525507119028-ed4c629a60a3'),
    category: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Floral', 'Solid Black', 'Solid White'],
    stockStatus: 'Low stock',
  },
  {
    id: 'amazon-sunglasses',
    brand: 'amazon',
    name: 'Amazon Polarised Sunglasses',
    price: 89,
    compareAtPrice: 109,
    sku: 'AM-AC-6603',
    description: 'UV400 polarised lens sunglasses in a classic wayfarers shape.',
    image: img('photo-1511499767150-a48a237f0083'),
    category: 'Accessories',
    sizes: ['One size'],
    colors: ['Black', 'Tortoise', 'Clear'],
    stockStatus: 'In stock',
  },
];

export const demoCategories = [
  'Best Sellers',
  'New Arrivals',
  'Shirts',
  'Pants',
  'Dresses',
  'Jackets',
  'Accessories',
] as const;

export function productsForBrand(brand: DemoBrandId) {
  return demoProducts.filter((product) => product.brand === brand);
}

export function findProduct(productId: string) {
  return demoProducts.find((product) => product.id === productId);
}

export function detectDemoBrand(input: string) {
  const lowered = input.toLowerCase();
  if (lowered.includes('amazon')) return 'amazon' as const;
  if (lowered.includes('zara')) return 'zara' as const;
  if (lowered.includes('hm') || lowered.includes('h&m')) return 'hm' as const;
  return null;
}

export function buildInviteMessage(name: string, brand: DemoBrandId, link: string, code: string) {
  const store = demoStores[brand];
  return `היי שכנים!\n${name} פותח/ת הזמנה קבוצתית מ-${store.name}.\n\nהצטרפו עכשיו — נגיע לסף ביחד ונחסוך על המשלוח לכולם.\n\n${link}\nקוד: ${code}`;
}
