export const IL_CITIES: readonly string[] = [
  'אבו גוש',
  'אור יהודה',
  'אור עקיבא',
  'אילת',
  'אלעד',
  'אריאל',
  'אשדוד',
  'אשקלון',
  'באר שבע',
  'בית שאן',
  'בית שמש',
  'בני ברק',
  'בת ים',
  'גבעת שמואל',
  'גבעתיים',
  'גן יבנה',
  'דימונה',
  'הוד השרון',
  'הרצליה',
  'חדרה',
  'חולון',
  'חיפה',
  'טבריה',
  'טירת כרמל',
  'יבנה',
  'יהוד',
  'ירושלים',
  'כפר סבא',
  'כרמיאל',
  'לוד',
  'מודיעין',
  'מודיעין עילית',
  'מעלה אדומים',
  'נהריה',
  'נס ציונה',
  'נצרת',
  'נוף הגליל',
  'נתיבות',
  'נתניה',
  'עכו',
  'עפולה',
  'פתח תקווה',
  'צפת',
  'קריית אונו',
  'קריית אתא',
  'קריית ביאליק',
  'קריית גת',
  'קריית ים',
  'קריית מוצקין',
  'קריית שמונה',
  'ראש העין',
  'ראשון לציון',
  'רחובות',
  'רמלה',
  'רמת גן',
  'רמת השרון',
  'רעננה',
  'שדרות',
  'תל אביב',
  'Tel Aviv',
  'Jerusalem',
  'Haifa',
  'Ramat Gan',
  'Givatayim',
  'Bnei Brak',
  'Petah Tikva',
  'Rishon LeZion',
  'Holon',
  'Bat Yam',
  'Netanya',
  'Herzliya',
  'Ra’anana',
  'Kfar Saba',
  'Ashdod',
  'Ashkelon',
  'Beer Sheva',
] as const;

export function matchCities(query: string, limit = 7): string[] {
  const q = query.trim().toLocaleLowerCase();
  if (!q) return [];
  return IL_CITIES.filter((city) => city.toLocaleLowerCase().includes(q)).slice(0, limit);
}
